name: VitalTp
version: @version@
main: com.tamrielnetwork.vitaltp.VitalTp
api-version: 1.17
authors: [ Tamriel Network ]
website: https://tamriel.site
description: Gives players the ability to teleport to each other.
commands:
  vitaltp:
    description: "Main command"
    usage: "/vitaltp tp/tphere <player>"
permissions:
  vitaltp.tp:
    description: "Permission to teleport to others"
    default: op
  vitaltp.tphere:
    description: "Permission to teleport others to you"
    default: op